name: Build and Test React Application

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branches
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          cd tests-practice
          npm ci
          npm run build --if-present
          npm test
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: tests-practice/build
          if-no-files-found: error
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate build version
        id: build_version
        run: |
          build_version="${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
          cd tests-practice
          git config --global user.email "jeanbernard_doffemont@yahoo.fr"
          git config --global user.name "JB-Doffemont"
          git tag v0.1.0-${build_version} -a -m "build render ${build_version}"
          npm version --allow-same-version from-git

      - name: Update README with build version
        run: |
              echo "Build Version: ${build_version}" >> tests_practice/README.md

    # Deploy Job
  deploy:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy Pages
      id-token: write #to verify the deployment originates from an appropriate source

    # Add a dependency to the build job
    needs: build_test
    # Specify runner + deployment step
    steps:
      - name: Deply to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
